### PR TITLE
Add nav changes for smaller screens

### PR DESCRIPTION
**Pull request by vormwald**
### Problem

The Global Styles I added didn't account for media break points, and the site looks bad on mobile

### Solution

Resize the logo, and change some padding to make it look better!

### CODE REVIEW

**Comment by vormwald** [comment]
@lannonbr yep, good observation... adding some more styles

**Comment by vormwald** [comment]
@lannonbr I pushed a change that looks good on my phone. Lemme know 👍

**Comment by lannonbr** [comment]
Hmm, this is very picky that it does feel cramped but it could be resolved later on. Opened it with my phone as well and it is alright for the most part.

**Comment by vormwald** [comment]
Yeah, I forgot to create this issue https://github.com/syracuseio/syracuseio/issues/46 to move the links into a menu button.  That's the long term solution.

This is might be good enough for launch?

**Comment by lannonbr** [comment]
Yeah I'd say it's good for now :shipit:

**Pull request merged**
